### ISSUE TITLE
Module controllers: how to migrate the System to Symfony smoothly?

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#11]
My quick opinion:

* the current system should work and be deprecated in 1.7.x
* we document "only" a new way to do it, and it will be the only way to do in 1.8.x

What do you think?

**Comment by PierreRambaud** [comment]
I'm agree with you. 
We need to think now about how to migrate. But what do you mean by the "System"? Is it front? back? Installer? If you mean every components, maybe it will be a 2.0? :smile:

**Comment by PierreRambaud** [comment]
If we think about what we exactly want for the next release, how we want to create a module, it will be easier to discuss about the implementation and how old modules and new modules can live together.

More, we need to know what a module can do? Register hooks, routing, displaying content, be part of the API? 
We need an explicit list, thinking about what we keep and what we want to add in the future.

Is there a lifecycle diagram (for module) available like VueJs ? (https://vuejs.org/images/lifecycle.png)

**Comment by mickaelandrieu** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/9153 (thanks @sarjon)

**Comment by eternoendless** [comment]
I agree on your first 3 bullet points, however the 4th we should try to avoid as Smarty belongs to the past. We should discourage use of if as much as we can. In fact, it should be fully deprecated so that we can get rid of it on the next major.
