### ISSUE TITLE
Define which content should be in cookie and which one should be in session.

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#16]
Docs

* [Secure Session Management With Cookies for Web Applications](https://crypto.stanford.edu/cs142/papers/web-session-management.pdf)
* [Hardened Stateless Session Cookies](http://sec.cs.ucl.ac.uk/users/smurdoch/papers/protocols08cookies.pdf)
* [OWASP](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet)

What is important here:

* Security over Scaling
* Scaling over Developer Experience
* Developer Experience over Ease of Maintenance (maybe?)

**Comment by eternoendless** [comment]
Also: https://www.owasp.org/index.php/Session_Management_Cheat_Sheet

ping @PierreRambaud

**Comment by matks** [comment]
@PierreRambaud We want to archive this repository. If this topic is still relevant, can I create an issue in main repository with duplicated content ?
