### ISSUE TITLE
Define how sessions should be handled to allow horizontal scaling.

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#17]
Some docs:

* [Use PDO in Symfony](https://symfony.com/doc/current/doctrine/pdo_session_storage.html)
* [Horizontal scaling of PHP applications](https://www.sitepoint.com/horizontal-scaling-php-apps/)
* [Scale horizontally](https://blog.rackspace.com/pillars-of-cloudiness-no-3-scaling-horizontally)
* [Maximizing PHP 7 Performance with NGINX, Part 2: Multiple Servers and Load Balancing](https://www.nginx.com/blog/maximizing-php-7-performance-with-nginx-part-ii-multiple-servers-and-load-balancing/)
* [Horizontally Scaling PHP Applications: A Practical Overview](https://blog.digitalocean.com/horizontally-scaling-php-applications/)
* [Horizontally web scalable applications](https://inviqa.com/blog/horizontally-scalable-web-applications)
* [How to scale PHP applications](https://www.slideshare.net/e.zimuel/how-to-scale-php-applications)
* [Why your code doesn't scale](https://www.mullie.eu/why-your-code-doesnt-scale/)
* [Configuring Sessions and Save Handlers](https://symfony.com/doc/3.4/components/http_foundation/session_configuration.html)

This is something that needs to be discussed because the current behavior of PrestaShop 1.7 for Symfony pages is to use the native temporary filesystem of PHP aka "native session handling". Using filesystem make the horizontal scaling hard to do, because we need to manage the synchronization of files across multiples servers to keep the access to the back office.

In legacy pages, it works well because of the Cookie store all the information needed by the Session to keep the user logged. See [More information in PrestaShop 1.6 docs](http://doc.prestashop.com/display/PS16/Managing+Cookies).

![cookie_legacy](https://user-images.githubusercontent.com/1247388/40209645-c7f630d2-5a40-11e8-9089-c1d20096d79b.png)

While in Symfony / newly migrated pages, you have almost no information stored in cookies:

![symfony](https://user-images.githubusercontent.com/1247388/40209759-7bbf02f6-5a41-11e8-8094-22116d3cf681.png)

All information to retrieve the user comes from the session:

![user_in_session](https://user-images.githubusercontent.com/1247388/40210052-2b6fe584-5a43-11e8-9cf1-5b4508e77e72.png)

**Comment by PierreRambaud** [comment]
We must allow users to define their own handler and we must offer the capability to use memcached, redis, mongo, fs, MySQL,... (When we have implement one, we can implement others easily)

**Comment by mickaelandrieu** [comment]
You mean something like that ? https://symfony.com/doc/3.4/components/http_foundation/session_configuration.html

**Comment by PierreRambaud** [comment]
Yep, exactly but with obviously a user interface :smile:

**Comment by rGaillard** [comment]
@mickaelandrieu furthermore the problem of the storage, the sessions are blocking (this is not the case of the cookies). Are you sure that you want to continue to add sessions in the software? :-1:

**Comment by PierreRambaud** [comment]
Of course we must keep the session for security reason. If you use cookies directly, clients can see and/or edit them themselves, but for session, the data is stored on the server side so client cannot access directly.

**Comment by rGaillard** [comment]
@PierreRambaud, this is not related to the security. In PrestaShop the cookies are encrypted with an additional checksum verification. So you can't see things or alter values of course...

**Comment by rGaillard** [comment]
@PierreRambaud and there is also an IP verification to avoid cookie hijacking which is currently not the case for the sessions in the 1.7.

**Comment by jocel1** [comment]
I agree with @rGaillard about the sessions which are blocking. It's not really an issue for the backoffice, but on the frontend, I don't like them, especially if a page is really slow to load (which could happen with prestashop :trollface: ), the loading of all the other pages will be stalled because of the sessions!

**Comment by jocel1** [comment]
FYI: https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/

**Comment by PierreRambaud** [comment]
@rGaillard If we can read the encrypted data, we can break it, even if there is a checksum, a salt or anything else, nothing is fully secure on internet :smile:.
Of course if you lock the filesystem you block the page, it's just obvious.  

FYI: 
https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Session_Management_Implementation 
> It is recommended to use these built-in frameworks versus building a home made one from scratch

**Comment by rGaillard** [comment]
@jocel1 it is also very annoying for the merchant in the Back-Office. Any slow page loading or slow ajax request will block the merchant in the current tab and the other tabs of its browser.... Many merchants complaints  about slow backoffice loading coming from modules which implements sessions... 

@PierreRambaud we use aes-256-ctr for the encryption which is pretty secure...

**Comment by mickaelandrieu** [comment]
@rGaillard we can't store everything in the cookie as its size is limited, we already have issues with 1.6 when the size is above 16ko.

Defining which data should store the cookie and which one should be in session is part of another issue, but to sum up: "no", we can't store everything in the cookie, and "yes" cookies are not that secure.

**Comment by PierreRambaud** [comment]
@rGaillard It's an algorithm so it can be broken. If you look back the history of cryptography, every algorithm gets broken eventually. That's why we make new algorithms. The question is how long it takes to figure out the math to break it?

**Comment by eternoendless** [comment]
This conversation really turns around after our discussion from last week 😁 

Bottom line:
* We shouldn't store identifiable data in the cookie, because encryption can (and will) be broken.
* Big cookies are also an issue because of client performance (who has to upload them) and eventually because of size limits. Remember that cookies need to be uploaded once for every HTTP request, and that many people don't have good upload speeds, specially on mobile networks.

**Comment by matks** [comment]
@PierreRambaud We want to archive this repository. If this topic is still relevant, can I create an issue in main repository with duplicated content ?
