### ISSUE TITLE
Migrate Sell > Orders > Invoices page

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#18]
Migration to Symfony to the page located here: `http://localhost/admin-dev/index.php?controller=AdminInvoices`.

[Docs to follow](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)

**Comment by rokaszygmantas** [comment]
Related PR: https://github.com/PrestaShop/PrestaShop/pull/9230

**Comment by mickaelandrieu** [comment]
Thanks @rokaszygmantas !

**Comment by rokaszygmantas** [comment]
Let's close this? :fireworks:

**Comment by mickaelandrieu** [comment]
yes :+1:
