### ISSUE TITLE
Migrate Improve > Design > Link Widgets

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#25]
Migration to Symfony to the page located here: http://localhost/admin-dev/index.php?controller=AdminLinkWidget

[Docs to follow](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)

Locked by https://github.com/PrestaShop/prestafony-project/issues/11

**Comment by PierreRambaud** [comment]
This one si a module, should it be move to the core? :D https://github.com/prestashop/ps_linklist

**Comment by mickaelandrieu** [comment]
If we don't have a quick solution for it, we may do it in 1.7.6 instead, I've just didn't noticed this page came from a module... this is another one use case we need to work on it.

**Comment by Quetzacoalt91** [comment]
Because this is not a critical feature expected in a shop (for instance in catalog mode). That's why we made it easily removed or replaced.

**Comment by mickaelandrieu** [comment]
so this should stay a module.

I don't have a solution right now for Module Controllers, I'll postpone this controller to 1.7.6, and during 1.7.5 we need to work on How we can migrate Module Controllers => https://github.com/PrestaShop/prestafony-project/issues/11

**Comment by mickaelandrieu** [comment]
@PierreRambaud This is now possible to do Module Controllers, see => https://github.com/PrestaShop/prestafony-project/blob/master/docs/create-your-own-modern-controllers.md
