### ISSUE TITLE
Manage multiple descriptions of PrestaShop version in code

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#32]
We sometimes need PrestaShop code to act according to the version of the Shop.

This can be for addons API, some [iframes](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php#L83) or retrieve [Localisation](https://github.com/PrestaShop/PrestaShop/pull/9116#discussion-diff-191833850R67) packs.

Currently, we end up with multiples helpers functions everywhere in the code.

It's time to extract a utility class, and declare it as a service so we can unit test it and rely on it everywhere.

WDYT?

**Comment by PierreRambaud** [comment]
Agree, service FTW!

**Comment by mickaelandrieu** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/9174
