### ISSUE TITLE
Migrate Improve > Payment > Preferences

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#35]
Migration to Symfony to the page located here: http://localhost/admin-dev/index.php?controller=AdminPaymentPreferences.

[Docs to follow](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)

**Comment by eternoendless** [comment]
This is being done by @sarjon

**Comment by mickaelandrieu** [comment]
It's merged => closed
