### ISSUE TITLE
Migrate Configure > Advanced Parameters > Database Backup

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#36]
Migration to Symfony to the page located here: http://localhost/admin-dev/index.php?controller=AdminBackup.

[Docs to follow](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)

**Comment by sarjon** [comment]
Migration PR https://github.com/PrestaShop/PrestaShop/pull/9447
