### ISSUE TITLE
Migrate Improve > Internation > Translations

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#39]
Migration to Symfony to the pages located here: http://localhost/admin-dev/index.php?controller=AdminTranslations.

[Docs to follow](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)

**Comment by rokaszygmantas** [comment]
https://github.com/PrestaShop/PrestaShop/pull/9449
