### ISSUE TITLE
JQuery vs Vuejs 2? Explain the Big Picture (frontend side)

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#4]
We have some pages in Back Office that use Vuejs already, but it was a mistake and the current idea is to migrate "step by step":

1. old legacy controller => Symfony controller
2. Smarty => Twig
3. SPA approach (with REST API from PrestaShop and Vuejs as a JS framework)

**Comment by PierreRambaud** [comment]
If you like VueJs you can check https://nuxtjs.org/ I'm a huge fan of this framework :)
