### ISSUE TITLE
Grid improvement: make the form available in controllers.

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#45]
For now, in Logs page we have a very custom form.

What we'd better do is re-use the form used in GridPresenter: as it's a Symfony from we have everything we want to retrieve dynamic data here.

**Comment by sarjon** [comment]
@mickaelandrieu we can already do that. :)

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php#L99

By the way, if any module alters grid definition with new filters (or removes default), this form will have all modifications. :+1:

**Comment by mickaelandrieu** [comment]
Where are the docs then? :p
