### ISSUE TITLE
Grid docs: update docs according to new improvements

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#59]
The documentation is not up to date with the Grid component:

* Redo the workflow part (there is no `createView()`) anymore
* Add a section to describe every Column Type
* Add a section for the rendering with Twig
* Add a section to explain Twig Grid native plugins (pagination, search, export, ...)

**Comment by sarjon** [comment]
@mickaelandrieu should docs be pushed to prestafony or docs repo?

**Comment by mickaelandrieu** [comment]
Hello @sarjon, we're waiting for review and merge of my pull request.

So you can already work on official docs repository now.
