### ISSUE TITLE
Decouple filters & columns definition

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#62]
I have noticed that most 3rd party Grids provide separate definition for fields (in our case columns) and filters.

Also, if you check Catalog page in Back Office, you will see that there's more filters that columns:

![catalog_filters](https://user-images.githubusercontent.com/15143151/43738719-45652fd8-99ce-11e8-9535-029be29f8085.png)

This could be easily implemented into grid. What we can do is update `Definition` with `getFilters()` method and each grid definition factory could define (if needed) their filters. This change would require very minimal change (move filters from columns definition to separate method) to Grid component.

**Comment by mickaelandrieu** [comment]
Go for it :)
