### ISSUE TITLE
[Grid] Make a learning module for the community

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#63]
Use cases of the module:

* A column need to be changed from position 2 to 4
* A column name at position 1 needs to be changed
* A new column with data from a custom table needs to be added at position 3, name "only_viewed_by_admin" (boolean type/value)
* Only administrators can see rows with "only_viewed_by_admin" equals true
* The template of column 4 needs to be changed and this change shouldn't be applied to others grids.
* Everything must be really commented so if we give the module to the community, they can work with Grids as easy as we do.

> Do I miss something interesting to be tested? Add it ;)

**Comment by sarjon** [comment]
Ill do that after https://github.com/PrestaShop/PrestaShop/pull/9442 and https://github.com/PrestaShop/PrestaShop/pull/9402

**Comment by sarjon** [comment]
Module in WIP -> https://github.com/sarjon/demo-grid-module
