### ISSUE TITLE
[Hooks] How to get one and only one system to manage both hooks and Symfony events?

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#64]
TBD and discussed

Some WIP here: https://github.com/PrestaShop/PrestaShop/pull/9437 (Introducing HookDispatcherInterface)

**Comment by PierreRambaud** [comment]
Hooks are simple events. 
Manipulating the EventDispatcher can be a solution:

```php
$this->getEventDispatcher()->dispatch('actionCartSave', [...]);
```

and can be called with services configuration:
```yml
tags:
    - { name: kernel.event_listener, event: actionCartSave, method: onActionCartSave }
```

**Comment by mickaelandrieu** [comment]
Hooks are not that simple at all and hook system is not based on Observer pattern.

At the moment, hooks can:
* display data (like a partial response)
* change data
* aggregate data
* can't be stopped
* can't stop the propagation
* doesn't have specified priority

At the moment, events:
* can manipulate the data (though the returned response is a data)
* doesnt return any display per se
* can be stopped
* can stop the propagation
* are priorized by design
* are based on Observer pattern

The only chance to use the Event Dispatcher -> dispatch function is to respect the [interface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/EventDispatcherInterface.php#L34). We can't do that, and we shouldn't do that (the architecture needs to respect the domain and the use case, not to be changed by the framework).

**Comment by PierreRambaud** [comment]
First, we maybe need to improve hooks and add these capabilites:
* can be stopped
* can stop propagation 
* can have a priority 

_For example:_
I've a module `A`, `B` and `C` with `onActionCartSave`. I add a priority on module `B`, this one detects that a cart contains a specific voucher (or anything), it stops the propagation. (Better than current override)

More, we maybe need to add a wrapper around `Hooks` and `EventDispatcher`?

**Comment by mickaelandrieu** [comment]
> More, we maybe need to add a wrapper around Hooks and EventDispatcher?

isn't what we have done already? :angel:

**Comment by sarjon** [comment]
> First, we maybe need to improve hooks and add these capabilites:
>
>   * can be stopped
>   * can stop propagation
>   * can have a priority

i think that hooks should not be stopped. A lot of times you have module that heavily depends on some hook(s) to function properly, if there was some 3rd party module(s) that could stop hooks from execution, this could bring in a lot of confusion.

So, if hook is dispatched, all modules must be notified about it, otherwise, you may think that you have bug in your code (when client contacts you because your module is not working even though it is) or merchant that is using 2 or more modules which stops hooks that other module depends on may get unexpected behavior.

**Comment by mickaelandrieu** [comment]
> So, if hook is dispatched, all modules must be notified about it, otherwise, you may think that you have bug in your code (when client contacts you because your module is not working even though it is) or merchant that is using 2 or more modules which stops hooks that other module depends on may get unexpected behavior.

This won't happens as the Hook Dispatcher debugger will be here to tell you which hooks are dispatched and which modules have been used ;)

**Comment by sarjon** [comment]
i think still its bad idea, it will introduce unexpected behavior anyway, and it will take time both for developers to find out issue & confuse merchants. :/ 

also, if shop is in production, it may complicate things, as you wont see toolbar.
What is even worse (from my experience) when merchant buys a lot of modules from Addons Store or other 3rd party vendor and they are not working, it a hell to figure out why, do you see a problem now?
