### ISSUE TITLE
CRUD Form management

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#66]
Following the idea introduce in this PR https://github.com/PrestaShop/PrestaShop/pull/8908 for Configuration forms management, maybe we can have similar workflow for CRUD forms as well?

Below is an example workflow for Edit action of any Entity (in this case entity with ID 12):

![crud workflow](https://user-images.githubusercontent.com/15143151/44425515-c0038880-a594-11e8-83b3-2a3da5c5ab40.jpg)

As you can see it is very similar to Configuration forms management workflow, thus easy to learn and implement.

These could be class interfaces used for forms management:

![crud interfaces](https://user-images.githubusercontent.com/15143151/44425554-dc072a00-a594-11e8-97b0-91e72e8be72d.jpg)

**Comment by sarjon** [comment]
@mickaelandrieu wdyt?

**Comment by mickaelandrieu** [comment]
I think I want to know which tool do you use to do your sequence diagram :)

For the sequence/workflow/implementation stuff, it's up to @eternoendless for the most. I'm interested and where exactly you plan to dispatch hooks and what will be available in them: be careful to not give access to something that people can break :)

**Comment by sarjon** [comment]
i think it's the same tool as you use draw.io and i used UML elements https://prnt.sc/kld8z3 :+1: 

regarding extensibility, it could be same type of hooks as it is in Configuration `FormHandler`.
For example in `getForm()` / `getFormFor()` methods dispatched hook could be `action{entity_name}BuildForm` and in `save()` method it could be `action{entity_name}FormSave`.

**Comment by mickaelandrieu** [comment]
I think I'll quit PrestaShop to become some UML/draw.io guru soon :p

Ok for the extensibility.

**Comment by eternoendless** [comment]
Looking good 👍
