### ISSUE TITLE
How to make Grid javascripts easy to access in modules?

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#67]
This may be a question for you @eternoendless: looking at the learning module about grids, I've noticed the only way to retrieve Javascripts file from Core into module is to follow [the path](https://github.com/sarjon/demo-grid-module/blob/master/assets/js/admin/product/index.js#L1).

```js
import Grid from '../../../../../../admin-dev/themes/new-theme/js/components/grid/grid';
import FiltersResetExtension
  from "../../../../../../admin-dev/themes/new-theme/js/components/grid/extension/filters-reset-extension";
import SortingExtension
  from "../../../../../../admin-dev/themes/new-theme/js/components/grid/extension/sorting-extension";

const $ = window.$;

$(document).ready(() => {
  const productGrid = new Grid('demogrid_products');

  productGrid.addExtension(new FiltersResetExtension());
  productGrid.addExtension(new SortingExtension());
});
```

I see 1 issue here, as we can change the name of the "admin" folder, and also because everything is in admin/new-theme, what will happen when we will introduce back the admin themes?

My feeling here is that we should extract everything that is not related to pages (components, utils, useful functions) outside of `admin-dev` folder. Maybe by creating npm packages and new GitHub repositories, maybe by creating a new folder or re-using `js` folder... I don't know :)

**Comment by sarjon** [comment]
Noticed the same issue, however, once you finish module development and submit it to Marketplace or send it to client, you do this with compiled assets, so it works as it should.

But i think this could be improved of course, so source files could be updated on any environment without changing paths. :+1:
